-- ============================================================================
-- V1: SpringBootCRM base schema
-- ============================================================================
-- Compatible with H2 in PostgreSQL mode. Names are lower case (Hibernate physical
-- naming strategy). UUIDs for seed rows are set explicitly.
-- ============================================================================


-- ============================================================================
-- 1. CORE
-- ============================================================================

-- ----------------------------------------------------------------------------
-- USERS - accounts (UserAggregate, typeId=9001)
-- ----------------------------------------------------------------------------
-- The code/name columns, role_type_id/role_id (one role per
-- user) and interface_layout_* (the assigned interface)
-- are included in their final shape from the start.
-- password_hash is BCrypt; HIDDEN at field level (read only by the auth flow).
-- ----------------------------------------------------------------------------
CREATE TABLE users (
    id                        UUID          PRIMARY KEY,
    -- Catalog attributes
    code                      VARCHAR(50)   NOT NULL UNIQUE,
    name                      VARCHAR(200)  NOT NULL,
    username                  VARCHAR(100)  NOT NULL UNIQUE,
    email                     VARCHAR(200)  NOT NULL,
    display_name              VARCHAR(200),
    password_hash             VARCHAR(200)  NOT NULL,
    enabled                   BOOLEAN       NOT NULL DEFAULT TRUE,
    -- Role: AggregateReference<AccessRole, UUID> (nullable). 9100 = AccessRole.TYPE_ID.
    role_type_id              BIGINT,
    role_id                   UUID,
    -- Assigned interface: AggregateReference<InterfaceLayout, UUID> (nullable).
    -- NULL means the user gets the default mode. 9300 = InterfaceLayout.TYPE_ID.
    interface_layout_type_id  BIGINT,
    interface_layout_id       UUID,
    -- Per-instance ACL (AbstractAggregate) + per-user grants (UserAggregate)
    own_access                VARCHAR(4000),
    user_access               VARCHAR(4000),
    -- ---- AbstractAggregate audit ----
    version                   BIGINT        NOT NULL DEFAULT 0,
    created_at                TIMESTAMP,
    updated_at                TIMESTAMP,
    created_by_type_id        BIGINT,
    created_by_id             UUID,
    updated_by_type_id        BIGINT,
    updated_by_id             UUID
);
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_code     ON users (code);
CREATE INDEX idx_users_role_id  ON users (role_id);

-- ----------------------------------------------------------------------------
-- EVENT_OUTBOX — transactional event publishing (domain.core.eventing.OutboxEntity)
-- ----------------------------------------------------------------------------
CREATE TABLE event_outbox (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agg_type_id     BIGINT       NOT NULL,
    agg_id_raw      VARCHAR(200) NOT NULL,
    event_type      VARCHAR(200) NOT NULL,
    stable_name     VARCHAR(100) NOT NULL,
    version         INT          NOT NULL,
    payload_json    TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    published_at    TIMESTAMP
);
CREATE INDEX idx_outbox_published ON event_outbox (published_at);
CREATE INDEX idx_outbox_aggref    ON event_outbox (agg_type_id, agg_id_raw);


-- ============================================================================
-- 2. ACCESS / ROLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ACCESS_ROLES - catalog of permission presets (typeId=9100)
-- ----------------------------------------------------------------------------
-- access_template stores a serialized AccessMetricPayload (the same
-- AccessMetricJsonConverter as user.access).
-- User<->AccessRole is one-to-one through users.role_*,
-- so there is no separate user_assigned_roles m2m table.
-- ----------------------------------------------------------------------------
CREATE TABLE access_roles (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL UNIQUE,
    name                VARCHAR(200)  NOT NULL,
    description         VARCHAR(500),
    access_template     VARCHAR(4000) NOT NULL,
    enabled             BOOLEAN       NOT NULL DEFAULT TRUE,
    -- ---- AbstractAggregate audit ----
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID
);
CREATE INDEX idx_access_roles_code ON access_roles (code);


-- ============================================================================
-- 3. CATALOG INFRASTRUCTURE (code generation)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- REFERENCE_SEQUENCES - a per-typeId counter for CodeGenerator.nextFor(class).
-- SELECT ... FOR UPDATE on type_id serializes concurrent inserts (idempotency).
-- ----------------------------------------------------------------------------
CREATE TABLE reference_sequences (
    type_id   BIGINT PRIMARY KEY,
    next_seq  BIGINT NOT NULL DEFAULT 1
);


-- ============================================================================
-- 4. DOMAIN CATALOGS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CUSTOMERS (typeId=4001)
-- ----------------------------------------------------------------------------
-- Validation of the code and the allowed character set lives in the service layer.
-- The record date and author map to the AbstractAggregate audit fields (updated_at/updated_by).
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    notes               VARCHAR(500),
    email               VARCHAR(160),
    phone               VARCHAR(40),
    city                VARCHAR(120),
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID,
    CONSTRAINT uk_customers_code UNIQUE (code)
);
CREATE INDEX idx_customers_code ON customers (code);

-- Demo customers.
INSERT INTO customers (id, code, name, notes, email, phone, city, created_at) VALUES
    ('66666666-6666-6666-6666-000000000001', 'CUS000001', 'Northwind Trading',
     'Key account, renews in Q4.', 'ops@northwind.example', '+1 202 555 0143',
     'Boston', CURRENT_TIMESTAMP),
    ('66666666-6666-6666-6666-000000000002', 'CUS000002', 'Contoso Manufacturing',
     'Migrated from a competitor.', 'purchasing@contoso.example', '+1 312 555 0197',
     'Chicago', CURRENT_TIMESTAMP),
    ('66666666-6666-6666-6666-000000000003', 'CUS000003', 'Fabrikam Logistics',
     'Pilot project running.', 'hello@fabrikam.example', '+44 20 7946 0812',
     'London', CURRENT_TIMESTAMP);

-- ----------------------------------------------------------------------------
-- PRODUCTS (typeId=4002)
-- ----------------------------------------------------------------------------
-- A "code + name" catalog. The record date and author map to the audit fields of
-- AbstractAuditedAggregate (created_at/updated_at, created_by/updated_by).
-- CODE and NAME are unique.
-- ----------------------------------------------------------------------------
CREATE TABLE products (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    sku                 VARCHAR(40),
    unit_price          NUMERIC(12,2),
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID,
    CONSTRAINT uk_products_code UNIQUE (code),
    CONSTRAINT uk_products_name UNIQUE (name)
);
CREATE INDEX idx_products_code ON products (code);

-- Demo products. created_at is filled so that the
-- "Record date" column is visible right away (for UI-created rows Spring Data Auditing sets it).
INSERT INTO products (id, code, name, sku, unit_price, created_at) VALUES
    ('55555555-5555-5555-5555-000000000001', '1', 'Starter Plan',      'SKU-100',   49.00, CURRENT_TIMESTAMP),
    ('55555555-5555-5555-5555-000000000002', '2', 'Professional Plan', 'SKU-200',  149.00, CURRENT_TIMESTAMP),
    ('55555555-5555-5555-5555-000000000003', '3', 'Enterprise Plan',   'SKU-300',  499.00, CURRENT_TIMESTAMP),
    ('55555555-5555-5555-5555-000000000004', '4', 'Onboarding Service','SKU-900', 1200.00, CURRENT_TIMESTAMP);

-- ----------------------------------------------------------------------------
-- LEAD_SOURCES (typeId=4101)
-- ----------------------------------------------------------------------------
CREATE TABLE lead_sources (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID,
    CONSTRAINT uk_lead_sources_code UNIQUE (code)
);
INSERT INTO lead_sources (id, code, name) VALUES
    ('11111111-1111-1111-1111-000000000001', '1', 'Inbound Website'),
    ('11111111-1111-1111-1111-000000000002', '2', 'Partner Referral'),
    ('11111111-1111-1111-1111-000000000003', '3', 'Outbound Campaign'),
    ('11111111-1111-1111-1111-000000000004', '4', 'Trade Show');

-- ----------------------------------------------------------------------------
-- DEAL_STAGES (typeId=4102)
-- ----------------------------------------------------------------------------
CREATE TABLE deal_stages (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    probability         NUMERIC(5,2)  NOT NULL,
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID,
    CONSTRAINT uk_deal_stages_code UNIQUE (code)
);
INSERT INTO deal_stages (id, code, name, probability) VALUES
    ('22222222-2222-2222-2222-000000000001', '1', 'Qualification', 20.00),
    ('22222222-2222-2222-2222-000000000002', '2', 'Proposal',      50.00),
    ('22222222-2222-2222-2222-000000000003', '3', 'Negotiation',   75.00),
    ('22222222-2222-2222-2222-000000000004', '4', 'Closed Won',   100.00);

-- ----------------------------------------------------------------------------
-- DISCOUNTS (typeId=4103)
-- ----------------------------------------------------------------------------
-- "value" and "percent" are reserved words in H2 2.3+, hence the percent_value column
-- (@Column(name="percent_value") on the JPA entity).
-- ----------------------------------------------------------------------------
CREATE TABLE discounts (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL,
    name                VARCHAR(200)  NOT NULL,
    percent_value       NUMERIC(10,4) NOT NULL,
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID,
    CONSTRAINT uk_discounts_code UNIQUE (code)
);
INSERT INTO discounts (id, code, name, percent_value) VALUES
    ('33333333-3333-3333-3333-000000000001', '1', 'Volume 5%',      5.0000),
    ('33333333-3333-3333-3333-000000000002', '2', 'Volume 10%',    10.0000),
    ('33333333-3333-3333-3333-000000000003', '3', 'Partner 15%',   15.0000),
    ('33333333-3333-3333-3333-000000000004', '4', 'Renewal 7.5%',   7.5000),
    ('33333333-3333-3333-3333-000000000005', '5', 'Pilot 25%',     25.0000);

-- ----------------------------------------------------------------------------
-- DEALS (typeId=4104)
-- ----------------------------------------------------------------------------
-- A deal links a lead source, a pipeline stage and a customer. The links are
-- full
-- AggregateReferences (typeId+id), as in user_discounts. There is deliberately no FK: the ref
-- is polymorphic and integrity is enforced by ValidAggregateRefValidator.
-- lead_source_* -> lead_sources (4101); deal_stage_* -> deal_stages (4102); customer_* -> customers (4001).
-- ----------------------------------------------------------------------------
CREATE TABLE deals (
    id                      UUID          PRIMARY KEY,
    code                    VARCHAR(50)   NOT NULL,
    lead_source_type_id     BIGINT        NOT NULL,
    lead_source_id          UUID          NOT NULL,
    deal_stage_type_id      BIGINT        NOT NULL,
    deal_stage_id           UUID          NOT NULL,
    customer_type_id        BIGINT        NOT NULL,
    customer_id             UUID          NOT NULL,
    amount                  NUMERIC(14,2) NOT NULL,
    expected_close_date     DATE,
    own_access              VARCHAR(4000),
    version                 BIGINT        NOT NULL DEFAULT 0,
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    created_by_type_id      BIGINT,
    created_by_id           UUID,
    updated_by_type_id      BIGINT,
    updated_by_id           UUID,
    CONSTRAINT uk_deals_code UNIQUE (code)
);
CREATE INDEX idx_deals_lead_source    ON deals (lead_source_id);
CREATE INDEX idx_deals_deal_stage ON deals (deal_stage_id);
CREATE INDEX idx_deals_customer   ON deals (customer_id);

-- Demo deals (4101=LeadSource.TYPE_ID, 4102=DealStage.TYPE_ID, 4001=Customer.TYPE_ID).
-- created_at is filled so that the synthetic "Record date" column is visible right away
-- (for rows created through the UI Spring Data Auditing sets it).
INSERT INTO deals
    (id, code, lead_source_type_id, lead_source_id,
     deal_stage_type_id, deal_stage_id, customer_type_id, customer_id,
     amount, expected_close_date, created_at) VALUES
    ('44444444-4444-4444-4444-000000000001', 'DEA000001',
     4101, '11111111-1111-1111-1111-000000000001',
     4102, '22222222-2222-2222-2222-000000000002',
     4001, '66666666-6666-6666-6666-000000000001',
     24000.00, CAST(CURRENT_DATE + INTERVAL '30' DAY AS DATE), CURRENT_TIMESTAMP),
    ('44444444-4444-4444-4444-000000000002', 'DEA000002',
     4101, '11111111-1111-1111-1111-000000000002',
     4102, '22222222-2222-2222-2222-000000000003',
     4001, '66666666-6666-6666-6666-000000000002',
     58000.00, CAST(CURRENT_DATE + INTERVAL '60' DAY AS DATE), CURRENT_TIMESTAMP),
    ('44444444-4444-4444-4444-000000000003', 'DEA000003',
     4101, '11111111-1111-1111-1111-000000000004',
     4102, '22222222-2222-2222-2222-000000000001',
     4001, '66666666-6666-6666-6666-000000000003',
     9500.00, CAST(CURRENT_DATE + INTERVAL '14' DAY AS DATE), CURRENT_TIMESTAMP);

-- ----------------------------------------------------------------------------
-- INTERFACE_LAYOUTS - catalog of customized interfaces (typeId=9300)
-- ----------------------------------------------------------------------------
-- layout_json is a LayoutNode JSON tree (InterfaceLayoutJsonConverter, VARCHAR).
-- In production on Postgres this becomes JSONB + @JdbcTypeCode(SqlTypes.JSON).
-- defaultRepoAccess=READ_ONLY: any authenticated user may read, only an admin may write.
-- ----------------------------------------------------------------------------
CREATE TABLE interface_layouts (
    id                  UUID          PRIMARY KEY,
    code                VARCHAR(50)   NOT NULL UNIQUE,
    name                VARCHAR(200)  NOT NULL,
    layout_json         VARCHAR(8000),
    enabled             BOOLEAN       NOT NULL DEFAULT TRUE,
    -- ---- AbstractAuditedAggregate audit ----
    own_access          VARCHAR(4000),
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    created_by_type_id  BIGINT,
    created_by_id       UUID,
    updated_by_type_id  BIGINT,
    updated_by_id       UUID
);
CREATE INDEX idx_interface_layouts_code ON interface_layouts (code);


-- ============================================================================
-- 5. ACTIVITIES (typeId=5001)
-- ============================================================================
-- Activity extends the lean AbstractAggregate root: no
-- versioning, auditing or per-instance ACL. It carries only its declared attributes.
-- The row-level filter @AccessFiltered(userClaim=SELF_IDS) on owner_id makes Hibernate
-- add `owner_id IN (:selfIds)` (you see only your own activities); an admin bypasses it.
-- subject_* is a polymorphic UNION reference {User|Customer|LeadSource} (nullable).
-- ============================================================================
CREATE TABLE activities (
    id                  UUID          PRIMARY KEY,
    title               VARCHAR(200)  NOT NULL,
    description         VARCHAR(2000),
    starts_at           TIMESTAMP     NOT NULL,
    ends_at             TIMESTAMP     NOT NULL,
    -- AggregateReference<User, UUID> owner (required)
    owner_type_id       BIGINT        NOT NULL,
    owner_id            UUID          NOT NULL,
    -- Polymorphic "related object" reference (nullable)
    subject_type_id     BIGINT,
    subject_id          UUID
);
CREATE INDEX idx_activities_owner     ON activities (owner_id);
CREATE INDEX idx_activities_starts_at ON activities (starts_at);
CREATE INDEX idx_activities_subject   ON activities (subject_type_id, subject_id);


-- ============================================================================
-- 6. REGISTERS AND TABULAR PARTS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- EXCHANGE_RATES - the exchange rate register (typeId=9202)
-- ----------------------------------------------------------------------------
-- A free register: arbitrary columns, NO version/audit/own_access
-- (it extends AbstractAggregate directly).
-- ----------------------------------------------------------------------------
CREATE TABLE exchange_rates (
    id          UUID            PRIMARY KEY,
    rate_date   DATE            NOT NULL,
    currency_code VARCHAR(10)   NOT NULL,
    rate        NUMERIC(18,6)   NOT NULL
);
CREATE INDEX idx_exchange_rates_date     ON exchange_rates (rate_date);
CREATE INDEX idx_exchange_rates_currency ON exchange_rates (currency_code);
INSERT INTO exchange_rates (id, rate_date, currency_code, rate) VALUES
    ('99999999-0000-0000-0000-000000000001', CURRENT_DATE, 'USD', 1.000000),
    ('99999999-0000-0000-0000-000000000002', CURRENT_DATE, 'EUR', 0.920000),
    ('99999999-0000-0000-0000-000000000003', CURRENT_DATE, 'GBP', 0.790000);

-- ----------------------------------------------------------------------------
-- USER_DISCOUNTS - a tabular part of the User aggregate (typeId=9201)
-- ----------------------------------------------------------------------------
-- A special case of a register: no audit/version/own_access plus a mandatory
-- owner reference (owner_ref_*). Access is inherited from User (9001).
-- There is deliberately no FK: the ref is polymorphic (AbstractTabularPart), and integrity
-- is enforced by ValidAggregateRefValidator. discount_* -> discounts (4103).
-- ----------------------------------------------------------------------------
CREATE TABLE user_discounts (
    id                  UUID            PRIMARY KEY,
    owner_ref_type_id   BIGINT          NOT NULL,
    owner_ref_id        UUID            NOT NULL,
    discount_type_id BIGINT          NOT NULL,
    discount_id      UUID            NOT NULL,
    limit_percent       NUMERIC(18,6)   NOT NULL
);
CREATE INDEX idx_user_discounts_owner ON user_discounts (owner_ref_id);
CREATE INDEX idx_user_discounts_coef  ON user_discounts (discount_id);

-- A demo tabular row for the system admin (the id is fixed in AdminBootstrap).
-- No FK, so the insert is safe even before the users row exists (the admin is created
-- by a CommandLineRunner after the migrations). 9001=User.TYPE_ID, 4103=Discount.TYPE_ID,
-- discount_id '3333...0002' is the seed discount "Volume 10%".
INSERT INTO user_discounts
    (id, owner_ref_type_id, owner_ref_id, discount_type_id, discount_id, limit_percent) VALUES
    ('99999999-1111-0000-0000-000000000001',
     9001, '00000000-0000-0000-0000-000000000001',
     4103, '33333333-3333-3333-3333-000000000002', 10.000000);


-- ============================================================================
-- 7. UNIVERSAL REFERENCE LOOKUP (skeleton)
-- ============================================================================
-- An empty skeleton view: the real content (UNION ALL over every catalog) is generated
-- by the application at startup (ReferenceLookupViewSynchronizer) from MetadataSnapshot.
-- The skeleton keeps reports/BI on reference_lookup from failing before the first run.
-- reference_lookup_version is a service table for idempotent regeneration
-- (a hash of the sorted (typeId, table) list).
-- ============================================================================
CREATE VIEW reference_lookup AS
    SELECT CAST(NULL AS BIGINT)  AS type_id,
           CAST(NULL AS VARCHAR) AS id,
           CAST(NULL AS VARCHAR) AS code,
           CAST(NULL AS VARCHAR) AS name,
           CAST(NULL AS VARCHAR) AS display
    WHERE 1 = 0;

CREATE TABLE reference_lookup_version (
    id            INT          PRIMARY KEY,
    content_hash  VARCHAR(64)  NOT NULL,
    updated_at    TIMESTAMP
);


-- ============================================================================
-- 8. SEED reference_sequences (failsafe; CodeGenerator also has computeSeedNext)
-- ============================================================================
-- On a clean database the count-based values are: 9001->1 (users is empty at migration time;
-- the admin is created later), 4001->4, 4101->5, 4102->5, 4103->6.
-- Plain INSERT: V1 creates reference_sequences empty, and Flyway runs V1 exactly once.
-- (Portable SQL — H2's MERGE ... KEY(...) has no PostgreSQL equivalent.)
-- ============================================================================
INSERT INTO reference_sequences (type_id, next_seq)
VALUES (9001, (SELECT COUNT(*) + 1 FROM users));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4001, (SELECT COUNT(*) + 1 FROM customers));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4002, (SELECT COUNT(*) + 1 FROM products));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4101, (SELECT COUNT(*) + 1 FROM lead_sources));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4102, (SELECT COUNT(*) + 1 FROM deal_stages));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4103, (SELECT COUNT(*) + 1 FROM discounts));

INSERT INTO reference_sequences (type_id, next_seq)
VALUES (4104, (SELECT COUNT(*) + 1 FROM deals));
